### ISSUE TITLE
an alternative...

### ISSUE THREAD

**Issue by fastrgv** [ericsunplus/windows-cds#1]
Hi, I saw no email address but I wanted to notify you of my awkward alternative with a similar function:
https://github.com/fastrgv/Wnexd
which I created using Windows batch script files.
fastrgv@gmail.com

**Comment by ericsunplus** [comment]
Thanks for the comment. Actually I am now switching to [Clink](https://github.com/chrisant996/clink), it seems to have a more versatile directory history switch functionality
